{
 "title": "Astrolavos (Latencies)",
 "tags": [
  "devops",
  "kubernetes",
  "infrastructure",
  "astrolavos"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "source",
    "label": "Source Cluster",
    "query": {
     "query": "label_values(thanos_build_info, cluster)"
    }
   },
   {
    "name": "percentile",
    "label": "Percentile",
    "query": "P50 : 0.5, P90 : 0.9, P95 : 0.95, P99 : 0.99"
   },
   {
    "name": "dst",
    "label": "Destination",
    "query": {
     "query": "label_values(astrolavos_total_latency_seconds_bucket{cluster=\"$source\"}, endpoint)"
    }
   },
   {
    "name": "tag",
    "label": "Tag",
    "query": {
     "query": "label_values(astrolavos_total_latency_seconds_bucket{cluster=\"$source\", endpoint=~\"$dst\"}, tag)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Endpoint Latencies", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DNS Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(astrolavos_dns_latency_seconds_bucket{cluster=\"$source\", endpoint=~\"$dst\", tag=~\"$tag\"}[5m])) by (cluster, le, endpoint, tag))",
     "legendFormat": "{{cluster}} -->> {{endpoint}}-->> {{tag}}"
    }
   ]
  },
  {
   "title": "TCP Connection Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(astrolavos_conn_latency_seconds_bucket{cluster=\"$source\", endpoint=~\"$dst\", tag=~\"$tag\"}[5m])) by (cluster, le, endpoint, tag))",
     "legendFormat": "{{cluster}} -->> {{endpoint}} -->> {{tag}}"
    }
   ]
  },
  {
   "title": "TLS handshake Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(astrolavos_tls_latency_seconds_bucket{cluster=\"$source\", endpoint=~\"$dst\", tag=~\"$tag\"}[5m])) by (cluster, le, endpoint, tag))",
     "legendFormat": "{{cluster}} -->> {{endpoint}} -->> {{tag}}"
    }
   ]
  },
  {
   "title": "Got Connection Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(astrolavos_gotconn_latency_seconds_bucket{cluster=\"$source\", endpoint=~\"$dst\", tag=~\"$tag\"}[5m])) by (cluster, le, endpoint, tag))",
     "legendFormat": "{{cluster}} -->> {{endpoint}} -->> {{tag}}"
    }
   ]
  },
  {
   "title": "Time to First Byte Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(astrolavos_firstbyte_latency_seconds_bucket{cluster=\"$source\", endpoint=~\"$dst\", tag=~\"$tag\"}[5m])) by (cluster, le, endpoint, tag))",
     "legendFormat": "{{cluster}} -->> {{endpoint}} -->> {{tag}}"
    }
   ]
  },
  {
   "title": "Total Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum(rate(astrolavos_total_latency_seconds_bucket{cluster=\"$source\", endpoint=~\"$dst\", tag=~\"$tag\"}[5m])) by (cluster, le, endpoint, tag))",
     "legendFormat": "{{cluster}} -->> {{endpoint}} -->> {{tag}}"
    }
   ]
  },
  {
   "title": "Returned Status Codes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(astrolavos_requests_total{cluster=\"$source\", endpoint=~\"$dst\", tag=~\"$tag\"}[5m])) by (cluster, endpoint, status_code, tag)",
     "legendFormat": "{{cluster}} -->> {{endpoint}} - {{status_code}} -->> {{tag}}"
    }
   ]
  },
  {
   "title": "Returned Error Codes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(astrolavos_errors_total{cluster=\"$source\", endpoint=~\"$dst\", tag=~\"$tag\"}[5m])) by (cluster, endpoint, error, tag)",
     "legendFormat": "{{cluster}} --> {{endpoint}} - {{error}} -->> {{tag}}"
    }
   ]
  },
  {
   "title": "Error Rate (5xx %)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(astrolavos_requests_total{cluster=\"$source\", endpoint=~\"$dst\", status_code=~\"5.*\", tag=~\"$tag\"}[5m])) by (cluster, endpoint, tag) / sum(rate(astrolavos_requests_total{cluster=\"$source\", endpoint=~\"$dst\", tag=~\"$tag\"}[5m])) by (cluster, endpoint, tag)) * 100",
     "legendFormat": "{{cluster}} --> {{endpoint}} -->> {{tag}}"
    }
   ]
  }
 ]
}