{
 "title": "Astrolavos Network Metrics",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "PROMETHEUS_DS", "label": "Prometheus Data Source", "query": "prometheus" },
   { "name": "cluster", "label": "Cluster", "query": { "query": "label_values(infra_cluster)" } },
   {
    "name": "tag",
    "label": "Traffic Type",
    "query": {
     "query": "label_values(astrolavos_total_latency_seconds_count,tag)"
    }
   },
   {
    "name": "percentile",
    "label": "Percentile",
    "query": "p50 : 0.50, p90 : 0.90, p99 : 0.99"
   },
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": {
     "query": "label_values(astrolavos_total_latency_seconds_count{infra_cluster=\"$cluster\"},exported_endpoint)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "DNS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(astrolavos_dns_latency_seconds_bucket{tag=~\"$tag\", infra_cluster=~\"$cluster\", exported_endpoint=~\"$endpoint\"}[5m])) by (le, tag, exported_endpoint))",
     "legendFormat": "{{ tag }} - {{ exported_endpoint }} - {{ percentile }}"
    }
   ]
  },
  {
   "title": "Connection",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(astrolavos_conn_latency_seconds_bucket{tag=~\"$tag\", infra_cluster=~\"$cluster\", exported_endpoint=~\"$endpoint\"}[5m])) by (le, tag, exported_endpoint))",
     "legendFormat": "{{ tag }} - {{ exported_endpoint }} - {{ percentile }}"
    }
   ]
  },
  {
   "title": "Got Connection",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(astrolavos_gotconn_latency_seconds_bucket{tag=~\"$tag\", infra_cluster=~\"$cluster\", exported_endpoint=~\"$endpoint\"}[5m])) by (le, tag, exported_endpoint))",
     "legendFormat": "{{ tag }} - {{ exported_endpoint }} - {{ percentile }}"
    }
   ]
  },
  {
   "title": "TLS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(astrolavos_tls_latency_seconds_bucket{tag=~\"$tag\", infra_cluster=~\"$cluster\", exported_endpoint=~\"$endpoint\"}[5m])) by (le, tag, exported_endpoint))",
     "legendFormat": "{{ tag }} - {{ exported_endpoint }} - {{ percentile }}"
    }
   ]
  },
  {
   "title": "First Byte",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(astrolavos_firstbyte_latency_seconds_bucket{tag=~\"$tag\", infra_cluster=~\"$cluster\", exported_endpoint=~\"$endpoint\"}[5m])) by (le, tag, exported_endpoint))",
     "legendFormat": "{{ tag }} - {{ exported_endpoint }} - {{ percentile }}"
    }
   ]
  },
  {
   "title": "Total",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(astrolavos_total_latency_seconds_bucket{tag=~\"$tag\", infra_cluster=~\"$cluster\", exported_endpoint=~\"$endpoint\"}[5m])) by (le, tag, exported_endpoint))",
     "legendFormat": "{{ tag }} - {{ exported_endpoint }} - {{ percentile }}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(astrolavos_errors_total{tag=~\"$tag\", infra_cluster=~\"$cluster\", exported_endpoint=~\"$endpoint\"}[5m]))",
     "legendFormat": "{{ error }}"
    }
   ]
  }
 ]
}