{{- if and .Values.rbac.create .Values.rbac.clusterRole }}
apiVersion: rbac.authorization.k8s.io/{{ .Values.rbac.apiVersion }}
kind: ClusterRole
metadata:
  name: {{ template "astrolavos.fullname" . }}
  labels: {{ include "astrolavos.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - namespaces
    verbs:
      - '*'
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - 'get'
      - 'list'
      - 'watch'
{{- end }}
