groups:
  - name: astrolavos-istio-gateway-alerts
    rules:
    - alert: IstioGateway504Errors
      annotations:
        description: Istio gateway appears to be misbehaving for {{ $labels.endpoint }}
        grafana_url: https://grafana.thebeat.co/d/pubyLdEMk/astrolavos-latencies?orgId=1
        summary: Istio Gateway is returning 504 Errors
      expr: sum(rate(astrolavos_requests_total{status_code="504", endpoint=~".*api.*thebeat.co"}[5m])) > 1
      for: 30m
      labels:
        severity: critical

  - name: astrolavos-cronjob-network-alerts
    rules:
    - alert: TCPErrors
      expr: sum(rate(astrolavos_errors_total{tag="cronjob"}[5m])) > 1
      for: 11m
      labels:
        severity: critical
      annotations:
        summary: "Astrolavos network cronjob checks fail"
        description: "Astrolavos network cronjob checks failing"
        runbook: "https://github.com/taxibeat/runbooks/blob/master/kubernetes/28_astrolavos_checks.md"

    - alert: MissingAstrolavosCronjobMetrics
      expr: absent(astrolavos_requests_total{tag="cronjob"}) == 1
      for: 120m
      labels:
        severity: critical
      annotations:
        summary: "Astrolavos network cronjob tests don't emmit metrics anymore"
        description: "Astrolavos network cronjob tests are not emmiting metrics anymore and that might indicate problems of the cronjob"
        runbook: "https://github.com/taxibeat/runbooks/blob/master/kubernetes/28_astrolavos_checks.md"
