#!/usr/bin/env python3
"""Release helper for astrolavos.

The app and the Helm chart are released in lockstep: tag vX.Y.Z, chart
version X.Y.Z, chart appVersion X.Y.Z and image.tag vX.Y.Z always match.
This script owns the bump so CI and humans do exactly the same thing.

Subcommands:
  latest-tag             print the most recent vX.Y.Z tag (empty if none)
  next-version BUMP      print the tag a patch|minor|major bump would create
  bump VERSION           rewrite Chart.yaml / values.yaml / README.md for X.Y.Z
  release BUMP           bump, commit "chore(release): vX.Y.Z", tag, push

Only python3 and git are required (helm-docs runs through `go run`).
Set RELEASE_SKIP_BRANCH_CHECKS=1 to bypass the "clean main" preflight, which
CI needs because actions/checkout leaves HEAD detached.
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CHART_DIR = ROOT / "deploy" / "kubernetes"
CHART_YAML = CHART_DIR / "Chart.yaml"
VALUES_YAML = CHART_DIR / "values.yaml"
HELM_DOCS_VERSION = "1.11.0"
HELM_DOCS = f"github.com/norwoodj/helm-docs/cmd/helm-docs@v{HELM_DOCS_VERSION}"
# the release binary bakes its version in via ldflags; without it helm-docs
# drops the "Autogenerated ..." footer and the README churns
HELM_DOCS_LDFLAGS = f"-X main.version={HELM_DOCS_VERSION}"

TAG_RE = re.compile(r"^v(\d+)\.(\d+)\.(\d+)$")
BUMPS = ("patch", "minor", "major")


def log(msg: str) -> None:
    print(f"[release] {msg}", file=sys.stderr)


def die(msg: str) -> "NoReturn":  # noqa: F821
    print(f"[release] error: {msg}", file=sys.stderr)
    sys.exit(1)


def run(*cmd: str, check: bool = True, capture: bool = True) -> subprocess.CompletedProcess:
    return subprocess.run(cmd, cwd=ROOT, check=check, text=True, capture_output=capture)


def git(*args: str, **kw) -> str:
    return run("git", *args, **kw).stdout.strip()


# --- versions ---------------------------------------------------------------


def semver_key(tag: str) -> tuple[int, int, int]:
    m = TAG_RE.match(tag)
    if not m:
        raise ValueError(tag)
    return tuple(int(x) for x in m.groups())  # type: ignore[return-value]


def latest_tag() -> str | None:
    tags = [t for t in git("tag", "--list", "v*").splitlines() if TAG_RE.match(t)]
    return max(tags, key=semver_key) if tags else None


def next_version(bump: str, current: str | None) -> str:
    if bump not in BUMPS:
        die(f"bump must be one of {', '.join(BUMPS)}, got {bump!r}")
    if current is None:
        return "v0.1.0"
    major, minor, patch = semver_key(current)
    if bump == "major":
        return f"v{major + 1}.0.0"
    if bump == "minor":
        return f"v{major}.{minor + 1}.0"
    return f"v{major}.{minor}.{patch + 1}"


def chart_version() -> str:
    m = re.search(r"^version:\s*(\S+)\s*$", CHART_YAML.read_text(), re.M)
    if not m:
        die(f"no top-level version in {CHART_YAML}")
    return m.group(1)


# --- file edits ------------------------------------------------------------


def _sub_once(text: str, pattern: str, repl: str, what: str) -> str:
    new, n = re.subn(pattern, repl, text, count=1, flags=re.M)
    if n != 1:
        die(f"could not find {what}")
    return new


def bump_files(version: str) -> None:
    """Rewrite the chart and values for X.Y.Z (version given as vX.Y.Z)."""
    if not TAG_RE.match(version):
        die(f"version must look like vX.Y.Z, got {version!r}")
    bare = version[1:]

    chart = CHART_YAML.read_text()
    chart = _sub_once(chart, r"^version:\s*\S+\s*$", f"version: {bare}", "Chart.yaml version")
    chart = _sub_once(chart, r'^appVersion:\s*"?[^"\n]+"?\s*$', f'appVersion: "{bare}"', "Chart.yaml appVersion")
    CHART_YAML.write_text(chart)

    values = VALUES_YAML.read_text()
    # the `tag:` line directly under the top-level `image:` block
    values = _sub_once(
        values,
        r"^(image:\n(?:  [^\n]*\n)*?  tag:\s*)\S+\s*$",
        rf"\g<1>{version}",
        "values.yaml image.tag",
    )
    VALUES_YAML.write_text(values)
    log(f"Chart.yaml -> version/appVersion {bare}, values.yaml -> image.tag {version}")

    log("regenerating chart README with helm-docs")
    run("go", "run", "-ldflags", HELM_DOCS_LDFLAGS, HELM_DOCS, "--chart-search-root", str(CHART_DIR), capture=False)


# --- preflight -------------------------------------------------------------


def require_clean_main() -> None:
    if os.environ.get("RELEASE_SKIP_BRANCH_CHECKS") == "1":
        return
    if git("rev-parse", "--abbrev-ref", "HEAD") != "main":
        die("releases are cut from main (set RELEASE_SKIP_BRANCH_CHECKS=1 to bypass)")
    if git("status", "--porcelain"):
        die("working tree is not clean")
    run("git", "fetch", "--quiet", "origin", "main", "--tags")
    if git("rev-parse", "HEAD") != git("rev-parse", "origin/main"):
        die("local main differs from origin/main; pull first")


# --- commands --------------------------------------------------------------


def cmd_latest_tag(_: argparse.Namespace) -> None:
    print(latest_tag() or "")


def cmd_next_version(args: argparse.Namespace) -> None:
    print(next_version(args.bump, latest_tag()))


def cmd_bump(args: argparse.Namespace) -> None:
    bump_files(args.version)


def cmd_release(args: argparse.Namespace) -> None:
    require_clean_main()
    current = latest_tag()
    chart = chart_version()
    if current is not None and current[1:] != chart:
        die(f"latest tag {current} does not match chart version {chart}; fix the drift before releasing")
    version = next_version(args.bump, current)
    if git("tag", "--list", version):
        die(f"tag {version} already exists")

    bump_files(version)

    run("git", "add", str(CHART_YAML), str(VALUES_YAML), str(CHART_DIR / "README.md"))
    run("git", "commit", "--quiet", "-m", f"chore(release): {version}")
    run("git", "tag", "-a", version, "-m", f"astrolavos {version}")
    if args.dry_run:
        log(f"dry run: created commit and tag {version} locally, not pushing")
    else:
        branch = os.environ.get("RELEASE_BRANCH", "main")
        run("git", "push", "--quiet", "origin", f"HEAD:{branch}", version, capture=False)
        log(f"pushed release commit to {branch} and tag {version}")
    print(version)


def main() -> None:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = p.add_subparsers(dest="cmd", required=True)
    sub.add_parser("latest-tag").set_defaults(fn=cmd_latest_tag)
    n = sub.add_parser("next-version")
    n.add_argument("bump", choices=BUMPS)
    n.set_defaults(fn=cmd_next_version)
    b = sub.add_parser("bump")
    b.add_argument("version", help="vX.Y.Z")
    b.set_defaults(fn=cmd_bump)
    r = sub.add_parser("release")
    r.add_argument("bump", choices=BUMPS)
    r.add_argument("--dry-run", action="store_true", help="commit and tag locally without pushing")
    r.set_defaults(fn=cmd_release)
    args = p.parse_args()
    args.fn(args)


if __name__ == "__main__":
    main()
