name: Helm CI
on:
  push:
      paths:
      - 'deploy/kubernetes/**'

permissions:
  contents: read

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@9bc31f4ebc9c6b171d7bfbaa5d006ae7abdb4310 # v5
        with:
          version: v3.22.0

      - name: Install helm-unittest plugin
        run: helm plugin install https://github.com/helm-unittest/helm-unittest.git --version v1.0.3

      - name: Build Helm Dependencies
        working-directory: './deploy/kubernetes'
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm dep update .

      - name: Run Helm Lint
        working-directory: './deploy/kubernetes'
        run: |
          helm lint --strict .

      - name: Run Helm unit tests
        run: make helm-test

      - name: Run Helm Template
        working-directory: './deploy/kubernetes'
        run: |
          helm template .

      - name: Run Helm Package
        working-directory: './deploy/kubernetes'
        run: |
          helm package .
