name: "Close stale issues"
on:
  schedule:
  - cron: "0 15 * * 1-5"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v4
      with:
        repo-token: ${{ github.token }}
        stale-pr-message: 'This PR has been marked as stale due to inactivity'
        days-before-stale: 7
        days-before-close: 7
        exempt-pr-label: 'on-hold'
